import { VideoCard } from './types';

export const MOCK_VIDEOS: VideoCard[] = [
  {
    id: 'v1',
    city: 'Paris',
    country: 'France',
    title: 'Sunrise at Trocadéro',
    shortDesc: 'The early bird gets the Eiffel all to themselves.',
    priceRange: '€€',
    tags: ['Iconic', 'Viewpoint'],
    creatorHandle: '@paris_romance',
    mediaPlaceholder: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    category: 'activity',
    zone: '7th Arr.',
    type: 'video'
  },
  {
    id: 'v2',
    city: 'Paris',
    country: 'France',
    title: 'Le Comptoir de La Gastronomie',
    shortDesc: 'The best onion soup and foie gras in the city.',
    priceRange: '€€€',
    tags: ['Food', 'Authentic'],
    creatorHandle: '@foodie_paris',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?q=80&w=800',
    category: 'food',
    zone: 'Les Halles',
    type: 'image'
  },
  {
    id: 'v3',
    city: 'Tokyo',
    country: 'Japan',
    title: 'TeamLab Borderless',
    shortDesc: 'Lose yourself in a world of digital art and light.',
    priceRange: '€€',
    tags: ['Art', 'Immersive'],
    creatorHandle: '@tokyo_tech',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?q=80&w=800',
    category: 'activity',
    zone: 'Odaiba',
    type: 'image'
  },
  {
    id: 'v4',
    city: 'Tokyo',
    country: 'Japan',
    title: 'Omoide Yokocho',
    shortDesc: 'Memory Lane: Tiny yakitori stalls and retro vibes.',
    priceRange: '€',
    tags: ['Food', 'Nightlife'],
    creatorHandle: '@ninja_food',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=800',
    category: 'nightlife',
    zone: 'Shinjuku',
    type: 'image'
  },
  {
    id: 'v5',
    city: 'New York',
    country: 'USA',
    title: 'Top of the Rock',
    shortDesc: 'Skip the Empire State crowds for this view.',
    priceRange: '€€',
    tags: ['Skyline', 'Viewpoint'],
    creatorHandle: '@ny_high',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1496442226666-8d4a0e62e6e9?q=80&w=800',
    category: 'activity',
    zone: 'Midtown',
    type: 'image'
  },
  {
    id: 'v6',
    city: 'New York',
    country: 'USA',
    title: 'Katz\'s Delicatessen',
    shortDesc: 'The legendary pastrami sandwich that lives up to the hype.',
    priceRange: '€€',
    tags: ['Food', 'Iconic'],
    creatorHandle: '@deliman',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1519690889869-e705e59f72e1?q=80&w=800',
    category: 'food',
    zone: 'Lower East Side',
    type: 'image'
  },
  {
    id: 'v7',
    city: 'Bali',
    country: 'Indonesia',
    title: 'Uluwatu Sunset Bar',
    shortDesc: 'Cliffs, waves, and the most dramatic sunset in Bali.',
    priceRange: '€€€',
    tags: ['Sunset', 'Luxury'],
    creatorHandle: '@bali_babe',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?q=80&w=800',
    category: 'nightlife',
    zone: 'Uluwatu',
    type: 'image'
  },
  {
    id: 'v8',
    city: 'Bali',
    country: 'Indonesia',
    title: 'Tegalalang Rice Terrace',
    shortDesc: 'Walk through the emerald greens of Ubud.',
    priceRange: '€',
    tags: ['Nature', 'Photo-Op'],
    creatorHandle: '@ubud_explorer',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=800',
    category: 'activity',
    zone: 'Ubud',
    type: 'image'
  },
  {
    id: 'v9',
    city: 'London',
    country: 'UK',
    title: 'Sketch Afternoon Tea',
    shortDesc: 'Pink rooms and the most famous toilets in London.',
    priceRange: '€€€',
    tags: ['Food', 'Design'],
    creatorHandle: '@london_chic',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1579782522047-e23157585a44?q=80&w=800',
    category: 'food',
    zone: 'Mayfair',
    type: 'image'
  },
  {
    id: 'v10',
    city: 'London',
    country: 'UK',
    title: 'God\'s Own Junk Yard',
    shortDesc: 'A neon paradise in the heart of Walthamstow.',
    priceRange: '€',
    tags: ['Art', 'Hidden Gem'],
    creatorHandle: '@neon_hunter',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?q=80&w=800',
    category: 'activity',
    zone: 'Walthamstow',
    type: 'image'
  }
];
