import { VideoCard } from './types';

export const MOCK_VIDEOS: VideoCard[] = [
  {
    id: 'v1',
    city: 'Paris',
    country: 'France',
    title: 'Sunrise at Trocadéro',
    shortDesc: 'The early bird gets the Eiffel all to themselves.',
    priceRange: '€€',
    tags: ['Iconic', 'Viewpoint'],
    creatorHandle: '@paris_romance',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800&auto=format&fit=crop',
    category: 'activity',
    zone: '7th Arr.'
  },
  {
    id: 'v2',
    city: 'Paris',
    country: 'France',
    title: 'Le Comptoir de La Gastronomie',
    shortDesc: 'The best onion soup and foie gras in the city.',
    priceRange: '€€€',
    tags: ['Food', 'Authentic'],
    creatorHandle: '@foodie_paris',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?q=80&w=800&auto=format&fit=crop',
    category: 'food',
    zone: 'Les Halles'
  },
  {
    id: 'v3',
    city: 'Tokyo',
    country: 'Japan',
    title: 'TeamLab Borderless',
    shortDesc: 'Lose yourself in a world of digital art and light.',
    priceRange: '€€',
    tags: ['Art', 'Immersive'],
    creatorHandle: '@tokyo_tech',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=800&auto=format&fit=crop',
    category: 'activity',
    zone: 'Odaiba'
  },
  {
    id: 'v4',
    city: 'Tokyo',
    country: 'Japan',
    title: 'Omoide Yokocho',
    shortDesc: 'Memory Lane: Tiny yakitori stalls and retro vibes.',
    priceRange: '€',
    tags: ['Food', 'Nightlife'],
    creatorHandle: '@ninja_food',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=800&auto=format&fit=crop',
    category: 'nightlife',
    zone: 'Shinjuku'
  },
  {
    id: 'v5',
    city: 'New York',
    country: 'USA',
    title: 'Top of the Rock',
    shortDesc: 'Skip the Empire State crowds for this view.',
    priceRange: '€€',
    tags: ['Skyline', 'Viewpoint'],
    creatorHandle: '@ny_high',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=800&auto=format&fit=crop',
    category: 'activity',
    zone: 'Midtown'
  },
  {
    id: 'v6',
    city: 'New York',
    country: 'USA',
    title: 'Katz\'s Delicatessen',
    shortDesc: 'The legendary pastrami sandwich that lives up to the hype.',
    priceRange: '€€',
    tags: ['Food', 'Iconic'],
    creatorHandle: '@deliman',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?q=80&w=800&auto=format&fit=crop',
    category: 'food',
    zone: 'Lower East Side'
  },
  {
    id: 'v7',
    city: 'Bali',
    country: 'Indonesia',
    title: 'Uluwatu Sunset Bar',
    shortDesc: 'Cliffs, waves, and the most dramatic sunset in Bali.',
    priceRange: '€€€',
    tags: ['Sunset', 'Luxury'],
    creatorHandle: '@bali_babe',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=800&auto=format&fit=crop',
    category: 'nightlife',
    zone: 'Uluwatu'
  },
  {
    id: 'v8',
    city: 'Bali',
    country: 'Indonesia',
    title: 'Tegalalang Rice Terrace',
    shortDesc: 'Walk through the emerald greens of Ubud.',
    priceRange: '€',
    tags: ['Nature', 'Photo-Op'],
    creatorHandle: '@ubud_explorer',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?q=80&w=800&auto=format&fit=crop',
    category: 'activity',
    zone: 'Ubud'
  },
  {
    id: 'v9',
    city: 'London',
    country: 'UK',
    title: 'Sketch Afternoon Tea',
    shortDesc: 'Pink rooms and the most famous toilets in London.',
    priceRange: '€€€',
    tags: ['Food', 'Design'],
    creatorHandle: '@london_chic',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=800&auto=format&fit=crop',
    category: 'food',
    zone: 'Mayfair'
  },
  {
    id: 'v10',
    city: 'London',
    country: 'UK',
    title: 'God\'s Own Junk Yard',
    shortDesc: 'A neon paradise in the heart of Walthamstow.',
    priceRange: '€',
    tags: ['Art', 'Hidden Gem'],
    creatorHandle: '@neon_hunter',
    mediaPlaceholder: 'https://images.unsplash.com/photo-1526129318478-62ed807ebdf9?q=80&w=800&auto=format&fit=crop',
    category: 'activity',
    zone: 'Walthamstow'
  }
];
